# site settings
title: Data Visualizations 
subtitle: by Tyler Dominguez
email: t3634245@gmail.com

description:
    Tyler Dominguez<br>
    
    Data Analyst<br>
    
    Python, R<br>
    
    Tableau, ArcGIS<br>
# baseurl: # the subpath of your site, e.g. /blog
url: https://41-14.github.io # the base hostname & protocol for your site
author:
street_address: 
city: Gainesville
state: Florida
zip_code:
country: United States of America
phone: fortyonefourteen#4114

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/41-14
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/tyler-dominguez/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
