# site settings
title: Data Visualizations 
subtitle: by Tyler Dominguez
email: tyler.dominguez@yahoo.com
description: Tyler Dominguez<br />Data Analyst<br />Python, R<br /> Tableau, ArcGIS
baseurl: # the subpath of your site, e.g. /blog
url: https://41-14.github.io # the base hostname & protocol for your site
author:
street_address: 
city: Gainesville
state: FL
zip_code: 32608
country: United States of America
phone: (772) 577-0581

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/41-14
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/tyler-dominguez/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
